[package]
name = "shaderjoy-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "shaderjoy"
path = "src/main.rs"

[dependencies]
shaderjoy-core = { path = "../shaderjoy-core" }
shaderjoy-render = { path = "../shaderjoy-render" }
anyhow = "1.0"
iced.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
console-subscriber.workspace = true
